name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest  # Versão fixa para evitar filas
    timeout-minutes: 10    # Evita jobs "presos"
    steps:
      # Ping periódico para evitar timeouts
      - name: Prevent timeout
        run: echo "Workflow em progresso - $(date)"

      - name: Create output directory
        run: mkdir -p dist
      
      # Snake Animation
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: Benetti03
          svg_out_path: dist/github-contribution-grid-snake.svg

      # GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
